transforms:  # This should match your dbt_project.yml name
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST', 'ep-wispy-feather-abbmiom0-pooler.eu-west-2.aws.neon.tech') }}"
      user: "{{ env_var('DBT_POSTGRES_USER', 'neondb_owner') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD', 'npg_Eb9nIemH2olr') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT', 5432) }}"
      dbname: "{{ env_var('DBT_POSTGRES_DB', 'example') }}"
      schema: "{{ env_var('DBT_POSTGRES_SCHEMA', 'dbt') }}"
      threads: 4
      sslmode: require
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      retry_on_database_errors: true
      retry_all: false