transforms:  # This should match your dbt_project.yml name
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST') }}"
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT', 5432) | as_number }}"
      dbname: "{{ env_var('DBT_POSTGRES_DB', 'neondb') }}"
      schema: "{{ env_var('DBT_POSTGRES_SCHEMA', 'dev') }}"
      threads: 4
      sslmode: require
      keepalives_idle: 0
      connect_timeout: 10
      retries: 1
      retry_on_database_errors: true
      retry_all: false